export const armourJson = [
  {
    "id": 0,
    "name": "你不该看到这个盔甲",
    "path": "/img2/未装备.png",
    "level": 1,
    "price": 0,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 0,
    "maxmagicpoint": 0,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 0,
    "physicaldefense": 0,
    "magicdefense": 0,
  },
  {
    "id": 1,
    "name": "木盔甲",
    "path": "/img2/未装备.png",
    "level": 1,
    "price": 50,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 5,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 5,
    "armourclass": 10,
    "physicaldefense": 10,
    "magicdefense": 0,
  },
  {
    "id": 2,
    "name": "铁盔甲",
    "path": "/img2/未装备.png",
    "level": 2,
    "price": 300,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 400,
    "maxmagicpoint": 0,
    "sturdypoint": 25,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 30,
    "physicaldefense": 15,
    "magicdefense": 0,
  },
  {
    "id": 3,
    "name": "黄金盔甲",
    "path": "/img2/未装备.png",
    "level": 2,
    "price": 300,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 400,
    "maxmagicpoint": 0,
    "sturdypoint": 25,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 30,
    "physicaldefense": 15,
    "magicdefense": 0,
  },
  {
    "id": 4,
    "name": "钻石盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2000,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 0,
    "sturdypoint": 40,
    "stamina": 25,
    "dexterity": 0,
    "spiritualintuition": 5,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 100,
    "physicaldefense": 20,
    "magicdefense": 0,
  },
  {
    "id": 5,
    "name": "龙鳞钢甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2000,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 0,
    "sturdypoint": 40,
    "stamina": 25,
    "dexterity": 0,
    "spiritualintuition": 5,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 100,
    "physicaldefense": 20,
    "magicdefense": 0,
  },
  {
    "id": 6,
    "name": "凤羽甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2000,
    "types": 3,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1000,
    "maxmagicpoint": 200,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 15,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 10,
    "attack": 5,
    "armourclass": 80,
    "physicaldefense": 10,
    "magicdefense": 25,
  },
  {
    "id": 7,
    "name": "幽冥甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 1800,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1000,
    "maxmagicpoint": 0,
    "sturdypoint": 40,
    "stamina": 25,
    "dexterity": 0,
    "spiritualintuition": 5,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 100,
    "physicaldefense": 10,
    "magicdefense": 5,
  },
  {
    "id": 8,
    "name": "赤铜甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 800,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 800,
    "maxmagicpoint": 0,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 20,
    "attack": 0,
    "armourclass": 60,
    "physicaldefense": 15,
    "magicdefense": 0,
  },
  {
    "id": 9,
    "name": "紫金甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 1800,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 0,
    "sturdypoint": 40,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 30,
    "armourclass": 100,
    "physicaldefense": 20,
    "magicdefense": 0,
  },
  {
    "id": 10,
    "name": "星陨甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2200,
    "types": 3,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1000,
    "maxmagicpoint": 300,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 20,
    "faith": 20,
    "attack": 0,
    "armourclass": 80,
    "physicaldefense": 10,
    "magicdefense": 10,
  },
  {
    "id": 11,
    "name": "狱炎甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 1800,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 0,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 10,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 30,
    "armourclass": 100,
    "physicaldefense": 10,
    "magicdefense": 10,
  },
  {
    "id": 12,
    "name": "红木盔甲",
    "path": "/img2/未装备.png",
    "level": 1,
    "price": 50,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 20,
    "physicaldefense": 10,
    "magicdefense": 0,
  },
  {
    "id": 13,
    "name": "针叶木盔甲",
    "path": "/img2/未装备.png",
    "level": 1,
    "price": 50,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 20,
    "physicaldefense": 10,
    "magicdefense": 0,
  },
  {
    "id": 14,
    "name": "棕榈木盔甲",
    "path": "/img2/未装备.png",
    "level": 1,
    "price": 50,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 20,
    "physicaldefense": 10,
    "magicdefense": 0,
  },
  {
    "id": 15,
    "name": "乌木盔甲",
    "path": "/img2/未装备.png",
    "level": 1,
    "price": 50,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 20,
    "physicaldefense": 10,
    "magicdefense": 0,
  },
  {
    "id": 16,
    "name": "防雪盔甲",
    "path": "/img2/未装备.png",
    "level": 2,
    "price": 300,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 400,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 5,
    "faith": 0,
    "attack": 0,
    "armourclass": 30,
    "physicaldefense": 10,
    "magicdefense": 5,
  },
  {
    "id": 17,
    "name": "铜盔甲",
    "path": "/img2/未装备.png",
    "level": 2,
    "price": 300,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 300,
    "maxmagicpoint": 50,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 5,
    "faith": 0,
    "attack": 0,
    "armourclass": 30,
    "physicaldefense": 10,
    "magicdefense": 5,
  },
  {
    "id": 18,
    "name": "锡盔甲",
    "path": "/img2/未装备.png",
    "level": 2,
    "price": 300,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 300,
    "maxmagicpoint": 50,
    "sturdypoint": 10,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 10,
    "faith": 0,
    "attack": 10,
    "armourclass": 30,
    "physicaldefense": 10,
    "magicdefense": 5,
  },
  {
    "id": 19,
    "name": "铂金盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 1800,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 100,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 20,
    "attack": 20,
    "armourclass": 100,
    "physicaldefense": 15,
    "magicdefense": 10,
  },
  {
    "id": 20,
    "name": "黑曜石盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2000,
    "types": 1,
    "needhealthpoint": 0,
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0,
    "healthpoint": 1200,
    "maxmagicpoint": 0,
    "sturdypoint": 40,
    "stamina": -20,
    "dexterity": -30,
    "spiritualintuition": 20,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 120,
    "physicaldefense": 40,
    "magicdefense": 0
  },
  {
    "id": 21,
    "name": "流星盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 800,
    "types": 3,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 600,
    "maxmagicpoint": 150,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 20,
    "faith": 0,
    "attack": 0,
    "armourclass": 50,
    "physicaldefense": 10,
    "magicdefense": 10,
  },
  {
    "id": 22,
    "name": "死灵盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 1000,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 800,
    "maxmagicpoint": 100,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 20,
    "faith": 0,
    "attack": 10,
    "armourclass": 50,
    "physicaldefense": 10,
    "magicdefense": 10,
  },
  {
    "id": 23,
    "name": "远古暗影盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 1800,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 100,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 20,
    "faith": 0,
    "attack": 20,
    "armourclass": 90,
    "physicaldefense": 10,
    "magicdefense": 20,
  },
  {
    "id": 24,
    "name": "暗影盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 800,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 600,
    "maxmagicpoint": 100,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 15,
    "faith": 0,
    "attack": 15,
    "armourclass": 60,
    "physicaldefense": 10,
    "magicdefense": 10,
  },
  {
    "id": 25,
    "name": "猩红盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 800,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 800,
    "maxmagicpoint": 0,
    "sturdypoint": 40,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 60,
    "physicaldefense": 10,
    "magicdefense": 10,
  },
  {
    "id": 26,
    "name": "熔岩盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2000,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1300,
    "maxmagicpoint": 0,
    "sturdypoint": 40,
    "stamina": 10,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 100,
    "physicaldefense": 15,
    "magicdefense": 0,
  },
  {
    "id": 27,
    "name": "蜘蛛盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 1000,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1000,
    "maxmagicpoint": 50,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 20,
    "faith": 0,
    "attack": 0,
    "armourclass": 50,
    "physicaldefense": 0,
    "magicdefense": 15,
  },
  {
    "id": 28,
    "name": "秘银盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2000,
    "types": 3,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 100,
    "sturdypoint": 30,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 20,
    "faith": 0,
    "attack": 0,
    "armourclass": 100,
    "physicaldefense": 15,
    "magicdefense": 5,
  },
  {
    "id": 29,
    "name": "钯金盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2000,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 100,
    "sturdypoint": 50,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 100,
    "physicaldefense": 10,
    "magicdefense": 15,
  },
  {
    "id": 30,
    "name": "山铜盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 1200,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 900,
    "maxmagicpoint": 100,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 60,
    "physicaldefense": 10,
    "magicdefense": 15,
  },
  {
    "id": 31,
    "name": "精金盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2200,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1400,
    "maxmagicpoint": 100,
    "sturdypoint": 40,
    "stamina": 10,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 100,
    "physicaldefense": 15,
    "magicdefense": 10,
  },
  {
    "id": 32,
    "name": "钛金盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2200,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1400,
    "maxmagicpoint": 100,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 100,
    "physicaldefense": 10,
    "magicdefense": 15,
  },
  {
    "id": 33,
    "name": "水晶刺客盔甲",
    "path": "/img2/未装备.png",
    "level": 2,
    "price": 300,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 400,
    "maxmagicpoint": 200,
    "sturdypoint": 10,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 15,
    "faith": 0,
    "attack": 0,
    "armourclass": 30,
    "physicaldefense": 10,
    "magicdefense": 15,
  },
  {
    "id": 34,
    "name": "寒霜盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 1000,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 800,
    "maxmagicpoint": 100,
    "sturdypoint": 20,
    "stamina": 20,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 10,
    "faith": 0,
    "attack": 0,
    "armourclass": 60,
    "physicaldefense": 10,
    "magicdefense": 15,
  },
  {
    "id": 35,
    "name": "禁戒盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 3000,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 2000,
    "maxmagicpoint": 70,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 20,
    "physicaldefense": 0,
    "magicdefense": 0,
  },
  {
    "id": 36,
    "name": "武僧盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 1000,
    "types": 2,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 600,
    "maxmagicpoint": 0,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 60,
    "physicaldefense": 10,
    "magicdefense": 15,
  },
  {
    "id": 37,
    "name": "神圣盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 1000,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 600,
    "maxmagicpoint": 50,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 30,
    "faith": 0,
    "attack": 0,
    "armourclass": 60,
    "physicaldefense": 15,
    "magicdefense": 10,
  },
  {
    "id": 38,
    "name": "远古神圣盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2200,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 300,
    "sturdypoint": 30,
    "stamina": 20,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 20,
    "faith": 0,
    "attack": 0,
    "armourclass": 100,
    "physicaldefense": 15,
    "magicdefense": 10,
  },
  {
    "id": 39,
    "name": "叶绿盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2200,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1400,
    "maxmagicpoint": 100,
    "sturdypoint": 30,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 100,
    "physicaldefense": 5,
    "magicdefense": 20,
  },
  {
    "id": 40,
    "name": "海龟盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2200,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1400,
    "maxmagicpoint": 100,
    "sturdypoint": 40,
    "stamina": 10,
    "dexterity": -10,
    "spiritualintuition": 0,
    "luckyvalue": -10,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 120,
    "physicaldefense": 25,
    "magicdefense": 0,
  },
  {
    "id": 41,
    "name": "甲虫盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2600,
    "types": 1,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1600,
    "maxmagicpoint": 150,
    "sturdypoint": 30,
    "stamina": 30,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 100,
    "physicaldefense": 20,
    "magicdefense": 5,
  },
  {
    "id": 42,
    "name": "幽灵盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2600,
    "types": 3,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 1200,
    "maxmagicpoint": 300,
    "sturdypoint": 30,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 20,
    "faith": 0,
    "attack": 0,
    "armourclass": 100,
    "physicaldefense": 5,
    "magicdefense": 20,
  },
  {
    "id": 43,
    "name": "英灵殿骑士盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 800,
    "types": 2,
    "needhealthpoint": 0,
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0,
    "healthpoint": 800,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 60,
    "physicaldefense": 15,
    "magicdefense": 10
  },
  {
    "id": 44,
    "name": "暗黑艺术家盔甲",
    "path": "/img2/未装备.png",
    "level": 3,
    "price": 800,
    "types": 3,
    "needhealthpoint": 0, //装备需求属性
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0, //
    "healthpoint": 600,
    "maxmagicpoint": 200,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 20,
    "faith": 0,
    "attack": 0,
    "armourclass": 60,
    "physicaldefense": 5,
    "magicdefense": 20,
  },
  {
    "id": 45,
    "name": "耀斑盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2600,
    "types": 1,
    "needhealthpoint": 0,
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0,
    "healthpoint": 1400,
    "maxmagicpoint": 100,
    "sturdypoint": 30,
    "stamina": 10,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 100,
    "physicaldefense": 25,
    "magicdefense": 0
  },
  {
    "id": 46,
    "name": "星旋盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2600,
    "types": 2,
    "needhealthpoint": 0,
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0,
    "healthpoint": 1200,
    "maxmagicpoint": 100,
    "sturdypoint": 20,
    "stamina": 10,
    "dexterity": 15,
    "spiritualintuition": 0,
    "luckyvalue": 25,
    "intelligence": 0,
    "faith": 0,
    "attack": 0,
    "armourclass": 100,
    "physicaldefense": 15,
    "magicdefense": 10
  },
  {
    "id": 47,
    "name": "星云盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2800,
    "types": 3,
    "needhealthpoint": 0,
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0,
    "healthpoint": 1200,
    "maxmagicpoint": 300,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 50,
    "faith": 0,
    "attack": 0,
    "armourclass": 100,
    "physicaldefense": 0,
    "magicdefense": 0
  },
  {
    "id": 48,
    "name": "星尘盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2600,
    "types": 2,
    "needhealthpoint": 0,
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0,
    "healthpoint": 1200,
    "maxmagicpoint": 100,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 20,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 100,
    "physicaldefense": 15,
    "magicdefense": 10
  },
  {
    "id": 49,
    "name": "布莱泽盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2600,
    "types": 2,
    "needhealthpoint": 0,
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0,
    "healthpoint": 1200,
    "maxmagicpoint": 0,
    "sturdypoint": 30,
    "stamina": -15,
    "dexterity": 15,
    "spiritualintuition": 10,
    "luckyvalue": 10,
    "intelligence": 5,
    "faith": 0,
    "attack": 15,
    "armourclass": 90,
    "physicaldefense": 10,
    "magicdefense": 20
  },
{
    "id": 50,
    "name": "黑夜骑兵盔甲",
    "path": "/img2/未装备.png",
    "level": 4,
    "price": 2600,
    "types": 1,
    "needhealthpoint": 0,
    "needmaxmagicpoint": 0,
    "needsturdypoint": 0,
    "needstamina": 0,
    "needdexterity": 0,
    "needspiritualintuition": 0,
    "needluckyvalue": 0,
    "needintelligence": 0,
    "needfaith": 0,
    "needattack": 0,
    "healthpoint": 1200,
    "maxmagicpoint": 0,
    "sturdypoint": 30,
    "stamina": -20,
    "dexterity": 0,
    "spiritualintuition": 10,
    "luckyvalue": 15,
    "intelligence": 5,
    "faith": 0,
    "attack": 30,
    "armourclass": 100,
    "physicaldefense": 10,
    "magicdefense": 15
  },

]
