export const raceJson =[
  //实例
  // {
  //   "id": 1,
  //   "name": "人类",
  //   "innateskill1": "", //天赋名称
  //   "innateskill1info1": "", //天赋描述
  //   "innateskill2": "",
  //   "innateskill1info2": "",
  //   "innateskill3": "",
  //   "innateskill1info3": "",
  //   "healthpoint": 1, //生命值
  //   "maxmagicpoint": 1, //最大魔力值
  //   "sturdypoint": 1, //体质
  //   "stamina": 1, //耐力
  //   "dexterity": 1, //敏捷
  //   "spiritualintuition": 1, //灵性直觉
  //   "luckyvalue": 1, //幸运值
  //   "intelligence": 1, //智力
  //   "faith": 1, //信仰
  //   "attack": 1, //力量
  //   "armourclass": 1, //护甲值
  //   "physicaldefense": 1, //物理抗性
  //   "magicdefense": 1, //魔法抗性
  // },
  {
    "id": 1,
    "name": "艾尔多利亚人",
    "innateskill1": "精湛的工艺技能",
    "innateskill1info1": "艾尔多利亚人以精湛的工艺技能闻名，他们擅长制造高质量的武器、护甲和艺术品。",
    "innateskill2": "自然亲和",
    "innateskill1info2": "艾尔多利亚人与自然和谐相处，能够与植物和动物建立深厚的联系，从中获得力量和智慧。",
    "innateskill3": "优越的战略洞察力",
    "innateskill1info3": "艾尔多利亚人在战略和战术上有出色的洞察力，能够迅速理解战场的局势并作出正确的决策。",
    "healthpoint": 100,
    "maxmagicpoint": 30,
    "sturdypoint": 10,
    "stamina": 5,
    "dexterity": 5,
    "spiritualintuition": 10,
    "luckyvalue": 5,
    "intelligence": 15,
    "faith": 20,
    "attack": 10,
    "armourclass": 5,
    "physicaldefense": 10,
    "magicdefense": 15,
  },
  {
    "id": 2,
    "name": "瓦洛利亚精灵",
    "innateskill1": "自然灵通",
    "innateskill1info1": "瓦洛利亚精灵与自然息息相关，他们具有与自然生物交流的能力，能够理解和影响自然的力量。",
    "innateskill2": "精灵优雅",
    "innateskill1info2": "瓦洛利亚精灵天生优雅灵动，身手敏捷，能够在森林和山脉中迅速穿行。",
    "innateskill3": "植物亲和",
    "innateskill1info3": "瓦洛利亚精灵对植物有着特殊的亲和力，能够促进植物生长和治愈受损的植物。",
    "healthpoint": 100,
    "maxmagicpoint": 100,
    "sturdypoint": 5,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 5,
    "luckyvalue": 5,
    "intelligence": 10,
    "faith": 20,
    "attack": 5,
    "armourclass": 5,
    "physicaldefense": 5,
    "magicdefense": 5,
  },
  {
    "id": 3,
    "name": "德拉肯海姆人",
    "innateskill1": "海洋精神",
    "innateskill1info1": "德拉肯海姆人与海洋息息相关，他们拥有超凡的海洋精神，能够在水下游弋自如。",
    "innateskill2": "水之祝福",
    "innateskill1info2": "德拉肯海姆人天生受到水之祝福，能够从水中汲取力量并治愈伤病。",
    "innateskill3": "渔猎技艺",
    "innateskill1info3": "德拉肯海姆人拥有卓越的渔猎技艺，能够在海洋中捕捞出丰富的食物资源。",
    "healthpoint": 200,
    "maxmagicpoint": 10,
    "sturdypoint": 10,
    "stamina": 5,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 5,
    "intelligence": 0,
    "faith": 10,
    "attack": 5,
    "armourclass": 5,
    "physicaldefense": 5,
    "magicdefense": 5,
  },
  {
    "id": 4,
    "name": "卢米娜拉人",
    "innateskill1": "光之护佑",
    "innateskill1info1": "卢米娜拉人天生受到光明力量的护佑，能够在危机时刻恢复体力。",
    "innateskill2": "灵巧手艺",
    "innateskill1info2": "卢米娜拉人以精湛的手艺和灵巧的双手著称，能够制造出精美且实用的物品。",
    "innateskill3": "精神韧性",
    "innateskill1info3": "卢米娜拉人的精神韧性极强，能够在极端压力下保持冷静和清醒。",
    "healthpoint": 100,
    "maxmagicpoint": 30,
    "sturdypoint": 5,
    "stamina": 5,
    "dexterity": 5,
    "spiritualintuition": 5,
    "luckyvalue": 10,
    "intelligence": 5,
    "faith": 15,
    "attack": 10,
    "armourclass": 10,
    "physicaldefense": 5,
    "magicdefense": 5,
  },
  {
    "id": 5,
    "name": "埃弗伦高等精灵",
    "innateskill1": "魔法亲和",
    "innateskill1info1": "埃弗伦高等精灵天生对魔法有着极高的亲和力，能够轻松掌握各种魔法技巧。",
    "innateskill2": "优雅敏捷",
    "innateskill1info2": "埃弗伦高等精灵拥有出众的身手和优雅的动作，使他们在战斗和探索中占据优势。",
    "innateskill3": "精神感知",
    "innateskill1info3": "埃弗伦高等精灵对环境和敌人的精神波动有着敏锐的感知，能够预见潜在的危险。",
    "healthpoint": 100,
    "maxmagicpoint": 100,
    "sturdypoint": 5,
    "stamina": 5,
    "dexterity": 10,
    "spiritualintuition": 10,
    "luckyvalue": 5,
    "intelligence": 25,
    "faith": 5,
    "attack": 5,
    "armourclass": 5,
    "physicaldefense": 5,
    "magicdefense": 5,
  },
  {
    "id": 6,
    "name": "温德米尔矮人",
    "innateskill1": "铁血之躯",
    "innateskill1info1": "温德米尔矮人的身体如同钢铁一般强壮，能够承受巨大的打击。",
    "innateskill2": "矿洞智慧",
    "innateskill1info2": "温德米尔矮人在矿石和宝石的辨别和采集上有着无与伦比的智慧。",
    "innateskill3": "战斗本能",
    "innateskill1info3": "温德米尔矮人在战斗中能够迅速做出反应，展现出非凡的战斗技巧。",
    "healthpoint": 300,
    "maxmagicpoint": 0,
    "sturdypoint": 15,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 10,
    "luckyvalue": 0,
    "intelligence": 5,
    "faith": 0,
    "attack": 10,
    "armourclass": 10,
    "physicaldefense": 10,
    "magicdefense": 10,
  },
  {
    "id": 7,
    "name": "提拉索恩人",
    "innateskill1": "龙之力",
    "innateskill1info1": "提拉索恩人天生强健，身体蕴含着龙族的无穷力量。",
    "innateskill2": "龙之护盾",
    "innateskill1info2": "提拉索恩人可以召唤出龙之护盾，抵御任何威胁，保护自己和同伴。",
    "innateskill3": "龙之感知",
    "innateskill1info3": "提拉索恩人拥有龙的敏锐感知能力，能够预知危险并发现隐藏的真相。",
    "healthpoint": 300,
    "maxmagicpoint": 0,
    "sturdypoint": 15,
    "stamina": 15,
    "dexterity": 0,
    "spiritualintuition": 15,
    "luckyvalue": 0,
    "intelligence": 5,
    "faith": 0,
    "attack": 15,
    "armourclass": 10,
    "physicaldefense": 10,
    "magicdefense": 10,
  },
  {
    "id": 8,
    "name": "维尔卡瑞尔精灵",
    "innateskill1": "自然之力",
    "innateskill1info1": "维尔卡瑞尔精灵天生与自然融为一体，他们可以利用自然的力量进行战斗和防御。",
    "innateskill2": "隐秘行者",
    "innateskill1info2": "维尔卡瑞尔精灵擅长在森林和其他自然环境中隐藏自己，敌人很难发现他们的踪迹。",
    "innateskill3": "自然治愈",
    "innateskill1info3": "维尔卡瑞尔精灵能够通过自然的力量迅速恢复自身和盟友的伤势。",
    "healthpoint": 100,
    "maxmagicpoint": 10,
    "sturdypoint": 5,
    "stamina": 5,
    "dexterity": 10,
    "spiritualintuition": 15,
    "luckyvalue": 15,
    "intelligence": 15,
    "faith": 20,
    "attack": 10,
    "armourclass": 5,
    "physicaldefense": 0,
    "magicdefense": 0
  },
  {
    "id": 9,
    "name": "艾尔法德龙裔",
    "innateskill1": "龙之力",
    "innateskill1info1": "艾尔法德龙裔拥有远古巨龙的血脉，体内蕴藏着强大的龙之力量，使他们在战斗中无往不利。",
    "innateskill2": "龙鳞护甲",
    "innateskill1info2": "艾尔法德龙裔的皮肤如同龙鳞般坚韧，能够抵挡大部分物理和魔法攻击。",
    "innateskill3": "龙焰吐息",
    "innateskill1info3": "艾尔法德龙裔可以喷吐出炽热的龙焰，对敌人造成毁灭性的伤害。",
    "healthpoint": 300,
    "maxmagicpoint": 0,
    "sturdypoint": 10,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 5,
    "faith": 10,
    "attack": 20,
    "armourclass": 15,
    "physicaldefense": 20,
    "magicdefense": 20
  },
  {
    "id": 10,
    "name": "瑟莱斯月影",
    "innateskill1": "月光庇护",
    "innateskill1info1": "瑟莱斯月影受到月光的庇护，夜晚的战斗力大幅提升，且能够在黑暗中看得清楚。",
    "innateskill2": "月神祝福",
    "innateskill1info2": "瑟莱斯月影能得到月神的祝福，使他们在战斗中更加灵活和精准。",
    "innateskill3": "影舞步",
    "innateskill1info3": "瑟莱斯月影擅长使用影舞步，在战斗中可以迅速移动，使敌人难以攻击到他们。",
    "healthpoint": 100,
    "maxmagicpoint": 0,
    "sturdypoint": 15,
    "stamina": 0,
    "dexterity": 15,
    "spiritualintuition": 20,
    "luckyvalue": 10,
    "intelligence": 10,
    "faith": 0,
    "attack": 5,
    "armourclass": 10,
    "physicaldefense": 5,
    "magicdefense": 5
  },
  {
    "id": 11,
    "name": "菲尼克斯火灵",
    "innateskill1": "火焰掌控",
    "innateskill1info1": "菲尼克斯火灵可以自由掌控火焰，他们的攻击带有火焰伤害，能燃烧敌人。",
    "innateskill2": "火之护盾",
    "innateskill1info2": "菲尼克斯火灵可以召唤火焰护盾来保护自己，减免所受的伤害。",
    "innateskill3": "烈焰新生",
    "innateskill1info3": "菲尼克斯火灵在濒死时有一定几率从烈焰中重生，恢复部分生命值。",
    "healthpoint": 100,
    "maxmagicpoint": 10,
    "sturdypoint": 5,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 10,
    "luckyvalue": 5,
    "intelligence": 15,
    "faith": 10,
    "attack": 10,
    "armourclass": 20,
    "physicaldefense": 0,
    "magicdefense": 20
  },
  {
    "id": 12,
    "name": "艾瑞达光明使者",
    "innateskill1": "光明之力",
    "innateskill1info1": "艾瑞达光明使者拥有强大的光明力量，能够净化邪恶并治愈盟友。",
    "innateskill2": "圣光庇护",
    "innateskill1info2": "艾瑞达光明使者受到圣光的庇护，能够减少所受的魔法伤害。",
    "innateskill3": "神圣审判",
    "innateskill1info3": "艾瑞达光明使者能够发动神圣审判，对邪恶生物造成巨大的伤害。",
    "healthpoint": 250,
    "maxmagicpoint": 5,
    "sturdypoint": 5,
    "stamina": 5,
    "dexterity": 5,
    "spiritualintuition": 5,
    "luckyvalue": 5,
    "intelligence": 5,
    "faith": 20,
    "attack": 5,
    "armourclass": 10,
    "physicaldefense": 5,
    "magicdefense": 10
  },
  {
    "id": 13,
    "name": "艾尔瑟瑞尔龙人",
    "innateskill1": "龙鳞护甲",
    "innateskill1info1": "艾尔瑟瑞尔龙人拥有坚硬的龙鳞，能够极大地减免物理伤害。",
    "innateskill2": "龙息喷吐",
    "innateskill1info2": "艾尔瑟瑞尔龙人能够喷出炽热的龙息，对敌人造成火焰伤害。",
    "innateskill3": "龙族飞行",
    "innateskill1info3": "艾尔瑟瑞尔龙人能够短暂飞行，迅速移动到战场的任意位置。",
    "healthpoint": 300,
    "maxmagicpoint": 0,
    "sturdypoint": 10,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 5,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 20,
    "physicaldefense": 20,
    "magicdefense": 0
  },
  {
    "id": 14,
    "name": "纳尔希尔精灵",
    "innateskill1": "森林守护",
    "innateskill1info1": "纳尔希尔精灵与森林有着深厚的联系，能够在森林中获得额外的防御和恢复。",
    "innateskill2": "自然之箭",
    "innateskill1info2": "纳尔希尔精灵能够射出充满自然能量的箭矢，对敌人造成额外的魔法伤害。",
    "innateskill3": "精灵步伐",
    "innateskill1info3": "纳尔希尔精灵步伐轻盈，能够迅速躲避敌人的攻击并进行反击。",
    "healthpoint": 100,
    "maxmagicpoint": 5,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 10,
    "faith": 0,
    "attack": 10,
    "armourclass": 15,
    "physicaldefense": 15,
    "magicdefense": 15
  },
  {
    "id": 15,
    "name": "瓦洛斯兽人",
    "innateskill1": "野性之力",
    "innateskill1info1": "瓦洛斯兽人体内蕴含着无穷的野性力量，能够在战斗中爆发出惊人的破坏力。",
    "innateskill2": "狂怒",
    "innateskill1info2": "瓦洛斯兽人在受到攻击时进入狂怒状态，提高攻击力和速度。",
    "innateskill3": "兽人皮肤",
    "innateskill1info3": "瓦洛斯兽人的皮肤厚实，能够减少受到的物理伤害。",
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 15,
    "armourclass": 15,
    "physicaldefense": 15,
    "magicdefense": 0
  },
  {
    "id": 16,
    "name": "德尔菲亚龙人",
    "innateskill1": "龙鳞护甲",
    "innateskill1info1": "德尔菲亚龙人拥有坚硬的龙鳞，能够极大地减免物理伤害。",
    "innateskill2": "龙息喷吐",
    "innateskill1info2": "德尔菲亚龙人能够喷出炽热的龙息，对敌人造成火焰伤害。",
    "innateskill3": "龙族飞行",
    "innateskill1info3": "德尔菲亚龙人能够短暂飞行，迅速移动到战场的任意位置。",
    "healthpoint": 400,
    "maxmagicpoint": 0,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 5,
    "faith": 0,
    "attack": 5,
    "armourclass": 20,
    "physicaldefense": 20,
    "magicdefense": 5
  },
  {
    "id": 17,
    "name": "卢米纳拉夜精灵",
    "innateskill1": "暗影隐匿",
    "innateskill1info1": "卢米纳拉夜精灵能够在黑暗中隐藏自己，使敌人难以发现。",
    "innateskill2": "夜视",
    "innateskill1info2": "卢米纳拉夜精灵拥有在黑暗中清晰视物的能力。",
    "innateskill3": "月光祝福",
    "innateskill1info3": "卢米纳拉夜精灵在月光下获得额外的力量和速度。",
    "healthpoint": 200,
    "maxmagicpoint": 5,
    "sturdypoint": 5,
    "stamina": 5,
    "dexterity": 15,
    "spiritualintuition": 15,
    "luckyvalue": 5,
    "intelligence": 10,
    "faith": 5,
    "attack": 10,
    "armourclass": 10,
    "physicaldefense": 10,
    "magicdefense": 10
  },
  {
    "id": 18,
    "name": "埃尔洛希尔火精灵",
    "innateskill1": "火焰之心",
    "innateskill1info1": "埃尔洛希尔火精灵天生拥有火焰之心，能够操控火焰进行攻击。",
    "innateskill2": "燃烧之怒",
    "innateskill1info2": "埃尔洛希尔火精灵在受到攻击时能够激发内心的怒火，提升攻击力。",
    "innateskill3": "火焰护盾",
    "innateskill1info3": "埃尔洛希尔火精灵能够召唤火焰护盾，减少受到的物理伤害。",
    "healthpoint": 300,
    "maxmagicpoint": 20,
    "sturdypoint": 10,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 5,
    "intelligence": 0,
    "faith": 0,
    "attack": 25,
    "armourclass": 10,
    "physicaldefense": 15,
    "magicdefense": 0
  },
  {
    "id": 19,
    "name": "法尔尼尔风精灵",
    "innateskill1": "疾风步",
    "innateskill1info1": "法尔尼尔风精灵能够在战斗中迅速移动，闪避敌人的攻击。",
    "innateskill2": "风刃",
    "innateskill1info2": "法尔尼尔风精灵能够召唤锋利的风刃，对敌人造成切割伤害。",
    "innateskill3": "风之屏障",
    "innateskill1info3": "法尔尼尔风精灵能够召唤风之屏障，减少受到的魔法伤害。",
    "healthpoint": 100,
    "maxmagicpoint": 5,
    "sturdypoint": 5,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 5,
    "luckyvalue": 10,
    "intelligence": 5,
    "faith": 0,
    "attack": 5,
    "armourclass": 5,
    "physicaldefense": 0,
    "magicdefense": 20
  },
  {
    "id": 20,
    "name": "瑟瑞尔水精灵",
    "innateskill1": "水之治愈",
    "innateskill1info1": "瑟瑞尔水精灵能够利用水元素治愈自身或队友的伤口。",
    "innateskill2": "冰冻之触",
    "innateskill1info2": "瑟瑞尔水精灵能够将水元素转化为冰冻之力，冻结敌人。",
    "innateskill3": "水遁",
    "innateskill1info3": "瑟瑞尔水精灵能够快速在水中移动，并在水中隐匿身形。",
    "healthpoint": 300,
    "maxmagicpoint": 20,
    "sturdypoint": 30,
    "stamina": 0,
    "dexterity": 15,
    "spiritualintuition": 5,
    "luckyvalue": 15,
    "intelligence": 0,
    "faith": 10,
    "attack": 0,
    "armourclass": 0,
    "physicaldefense": 0,
    "magicdefense": 0
  },
  {
    "id": 21,
    "name": "克雷斯泰尔光精灵",
    "innateskill1": "光之祝福",
    "innateskill1info1": "克雷斯泰尔光精灵能够用光之力量祝福自己或队友，提升防御。",
    "innateskill2": "光之箭",
    "innateskill1info2": "克雷斯泰尔光精灵能够射出充满光之能量的箭矢，对敌人造成魔法伤害。",
    "innateskill3": "光之护盾",
    "innateskill1info3": "克雷斯泰尔光精灵能够召唤光之护盾，减少受到的物理伤害。",
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 20,
    "luckyvalue": 20,
    "intelligence": 20,
    "faith": 5,
    "attack": 10,
    "armourclass": 10,
    "physicaldefense": 5,
    "magicdefense": 5
  },
  {
    "id": 22,
    "name": "阿尔特拉斯火精灵",
    "innateskill1": "烈焰之心",
    "innateskill1info1": "阿尔特拉斯火精灵拥有烈焰之心，能够操控火焰进行攻击。",
    "innateskill2": "火焰冲击",
    "innateskill1info2": "阿尔特拉斯火精灵能够释放火焰冲击波，对周围敌人造成火焰伤害。",
    "innateskill3": "火焰护盾",
    "innateskill1info3": "阿尔特拉斯火精灵能够召唤火焰护盾，减少受到的物理伤害。",
    "healthpoint": 200,
    "maxmagicpoint": 10,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 20,
    "faith": 0,
    "attack": 15,
    "armourclass": 15,
    "physicaldefense": 15,
    "magicdefense": 5
  },
  {
    "id": 23,
    "name": "纳迦利斯冰精灵",
    "innateskill1": "冰霜之触",
    "innateskill1info1": "纳迦利斯冰精灵能够将水元素转化为冰霜之力，冻结敌人。",
    "innateskill2": "冰墙",
    "innateskill1info2": "纳迦利斯冰精灵能够召唤冰墙，阻挡敌人的攻击并减缓其速度。",
    "innateskill3": "冰之护盾",
    "innateskill1info3": "纳迦利斯冰精灵能够召唤冰之护盾，减少受到的物理伤害。",
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 20,
    "faith": 0,
    "attack": 30,
    "armourclass": 30,
    "physicaldefense": 20,
    "magicdefense": 0
  },
  {
    "id": 24,
    "name": "阿拉曼瑟暗精灵",
    "innateskill1": "暗影潜行",
    "innateskill1info1": "阿拉曼瑟暗精灵能够在黑暗中隐藏自己，使敌人难以发现。",
    "innateskill2": "暗影箭",
    "innateskill1info2": "阿拉曼瑟暗精灵能够射出充满暗影能量的箭矢，对敌人造成魔法伤害。",
    "innateskill3": "暗影护盾",
    "innateskill1info3": "阿拉曼瑟暗精灵能够召唤暗影护盾，减少受到的物理伤害。",
    "healthpoint": 0,
    "maxmagicpoint": 0,
    "sturdypoint": 10,
    "stamina": 10,
    "dexterity": 15,
    "spiritualintuition": 15,
    "luckyvalue": 10,
    "intelligence": 15,
    "faith": 0,
    "attack": 15,
    "armourclass": 0,
    "physicaldefense": 15,
    "magicdefense": 5
  },
  {
    "id": 25,
    "name": "伊利尔雷巨人",
    "innateskill1": "雷霆之力",
    "innateskill1info1": "伊利尔雷巨人体内蕴含着强大的雷霆之力，能够在战斗中爆发出惊人的破坏力。",
    "innateskill2": "雷霆之怒",
    "innateskill1info2": "伊利尔雷巨人在受到攻击时进入雷霆之怒状态，提高攻击力和速度。",
    "innateskill3": "雷电护盾",
    "innateskill1info3": "伊利尔雷巨人能够召唤雷电护盾，减少受到的魔法伤害。",
    "healthpoint": 300,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 15,
    "armourclass": 40,
    "physicaldefense": 0,
    "magicdefense": 20
  },
  {
    "id": 26,
    "name": "维拉尼亚火巨人",
    "innateskill1": "火焰之怒",
    "innateskill1info1": "维拉尼亚火巨人拥有强大的火焰之怒，能够在战斗中释放火焰攻击敌人。",
    "innateskill2": "炎爆",
    "innateskill1info2": "维拉尼亚火巨人能够召唤火焰爆炸，对周围的敌人造成大量火焰伤害。",
    "innateskill3": "火焰之盾",
    "innateskill1info3": "维拉尼亚火巨人能够召唤火焰之盾，减少受到的物理伤害。",
    "healthpoint": 500,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 5,
    "intelligence": 10,
    "faith": 0,
    "attack": 10,
    "armourclass": 0,
    "physicaldefense": 15,
    "magicdefense": 0
  },
  {
    "id": 27,
    "name": "西尔瓦林植物精灵",
    "innateskill1": "自然之力",
    "innateskill1info1": "西尔瓦林植物精灵能够召唤自然之力，快速恢复自身或队友的生命值。",
    "innateskill2": "荆棘之触",
    "innateskill1info2": "西尔瓦林植物精灵能够召唤荆棘攻击敌人，使其行动缓慢。",
    "innateskill3": "树皮护盾",
    "innateskill1info3": "西尔瓦林植物精灵能够将自身覆盖树皮，减少受到的物理伤害。",
    "healthpoint": 200,
    "maxmagicpoint": 5,
    "sturdypoint": 15,
    "stamina": 0,
    "dexterity": 15,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 20,
    "attack": 15,
    "armourclass": 40,
    "physicaldefense": 10,
    "magicdefense": 0
  },
  {
    "id": 28,
    "name": "阿斯特拉影精灵",
    "innateskill1": "影遁",
    "innateskill1info1": "阿斯特拉影精灵能够在战斗中隐身，避免敌人的攻击。",
    "innateskill2": "暗影突袭",
    "innateskill1info2": "阿斯特拉影精灵能够从暗影中突袭敌人，造成高额伤害。",
    "innateskill3": "影之屏障",
    "innateskill1info3": "阿斯特拉影精灵能够召唤影之屏障，减少受到的魔法伤害。",
    "healthpoint": 0,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 10,
    "dexterity": 15,
    "spiritualintuition": 15,
    "luckyvalue": 10,
    "intelligence": 15,
    "faith": 5,
    "attack": 25,
    "armourclass": 0,
    "physicaldefense": 0,
    "magicdefense": 30
  },
  {
    "id": 29,
    "name": "埃尔达温光精灵",
    "innateskill1": "光辉之力",
    "innateskill1info1": "埃尔达温光精灵能够释放光辉之力，治疗自身或队友的伤口。",
    "innateskill2": "光之箭",
    "innateskill1info2": "埃尔达温光精灵能够射出光之箭，对敌人造成魔法伤害。",
    "innateskill3": "光之护盾",
    "innateskill1info3": "埃尔达温光精灵能够召唤光之护盾，减少受到的物理伤害。",
    "healthpoint": 100,
    "maxmagicpoint": 10,
    "sturdypoint": 15,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 10,
    "faith": 20,
    "attack": 10,
    "armourclass": 5,
    "physicaldefense": 20,
    "magicdefense": 5
  },
  {
    "id": 30,
    "name": "德鲁恩雷精灵",
    "innateskill1": "雷霆之击",
    "innateskill1info1": "德鲁恩雷精灵能够释放雷霆之击，对敌人造成电击伤害。",
    "innateskill2": "闪电奔袭",
    "innateskill1info2": "德鲁恩雷精灵能够迅速接近敌人，进行闪电般的攻击。",
    "innateskill3": "雷电屏障",
    "innateskill1info3": "德鲁恩雷精灵能够召唤雷电屏障，减少受到的魔法伤害。",
    "healthpoint": 200,
    "maxmagicpoint": 5,
    "sturdypoint": 10,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 10,
    "luckyvalue": 10,
    "intelligence": 5,
    "faith": 5,
    "attack": 5,
    "armourclass": 5,
    "physicaldefense": 5,
    "magicdefense": 10
  },
  {
    "id": 31,
    "name": "纳格瑞斯冰精灵",
    "innateskill1": "冰霜之触",
    "innateskill1info1": "纳格瑞斯冰精灵能够将水元素转化为冰霜之力，冻结敌人。",
    "innateskill2": "寒冰刺",
    "innateskill1info2": "纳格瑞斯冰精灵能够召唤寒冰刺攻击敌人，使其受到冰冻伤害。",
    "innateskill3": "冰之护盾",
    "innateskill1info3": "纳格瑞斯冰精灵能够召唤冰之护盾，减少受到的物理伤害。",
    "healthpoint": 200,
    "maxmagicpoint": 20,
    "sturdypoint": 10,
    "stamina": 10,
    "dexterity": 0,
    "spiritualintuition": 10,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 5,
    "attack": 10,
    "armourclass": 10,
    "physicaldefense": 15,
    "magicdefense": 5
  },
  {
    "id": 32,
    "name": "阿尔泰兰火巨人",
    "innateskill1": "烈焰之心",
    "innateskill1info1": "阿尔泰兰火巨人拥有烈焰之心，能够操控火焰进行攻击。",
    "innateskill2": "火焰冲击",
    "innateskill1info2": "阿尔泰兰火巨人能够释放火焰冲击波，对周围敌人造成火焰伤害。",
    "innateskill3": "火焰护盾",
    "innateskill1info3": "阿尔泰兰火巨人能够召唤火焰护盾，减少受到的物理伤害。",
    "healthpoint": 400,
    "maxmagicpoint": 20,
    "sturdypoint": 20,
    "stamina": 5,
    "dexterity": 10,
    "spiritualintuition": 10,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 5,
    "attack": 15,
    "armourclass": 20,
    "physicaldefense": 15,
    "magicdefense": 0
  },
  {
    "id": 33,
    "name": "萨卡利亚黑精灵",
    "innateskill1": "黑暗之触",
    "innateskill1info1": "萨卡利亚黑精灵能够释放黑暗之触，削弱敌人的力量。",
    "innateskill2": "暗影突袭",
    "innateskill1info2": "萨卡利亚黑精灵能够从暗影中突袭敌人，造成高额伤害。",
    "innateskill3": "暗影护盾",
    "innateskill1info3": "萨卡利亚黑精灵能够召唤暗影护盾，减少受到的魔法伤害。",
    "healthpoint": 0,
    "maxmagicpoint": 0,
    "sturdypoint": 10,
    "stamina": 10,
    "dexterity": 10,
    "spiritualintuition": 10,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 0,
    "physicaldefense": 0,
    "magicdefense": 20
  },
  {
    "id": 34,
    "name": "塞尔利亚水精灵",
    "innateskill1": "水之守护",
    "innateskill1info1": "塞尔利亚水精灵能够操控水元素进行攻击，并在受到攻击时自动治疗自己。",
    "innateskill2": "水波攻击",
    "innateskill1info2": "塞尔利亚水精灵能够释放水波攻击敌人，使其受到水属性伤害。",
    "innateskill3": "水之护盾",
    "innateskill1info3": "塞尔利亚水精灵能够召唤水之护盾，减少受到的物理伤害。",
    "healthpoint": 200,
    "maxmagicpoint": 100,
    "sturdypoint": 10,
    "stamina": 20,
    "dexterity": 0,
    "spiritualintuition": 20,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 10,
    "attack": 15,
    "armourclass": 15,
    "physicaldefense": 20,
    "magicdefense": 10
  },
  {
    "id": 35,
    "name": "暗影峡谷亡灵",
    "innateskill1": "灵魂吞噬",
    "innateskill1info1": "暗影峡谷亡灵能够吞噬敌人的灵魂，恢复自身的生命值并增强力量。",
    "innateskill2": "死亡缠绕",
    "innateskill1info2": "暗影峡谷亡灵能够释放死亡缠绕，使敌人陷入恐惧并持续受到伤害。",
    "innateskill3": "阴影步",
    "innateskill1info3": "暗影峡谷亡灵能够进入阴影状态，暂时避开所有攻击并增加移动速度。",
    "healthpoint": 600,
    "maxmagicpoint": 0,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 0,
    "physicaldefense": 10,
    "magicdefense": 10
  },
  {
    "id": 36,
    "name": "血月平原吸血鬼",
    "innateskill1": "鲜血汲取",
    "innateskill1info1": "血月平原吸血鬼能够从敌人身上汲取鲜血，迅速恢复自身生命值。",
    "innateskill2": "夜之拥抱",
    "innateskill1info2": "血月平原吸血鬼能够在夜晚增加攻击力和防御力，使自己更强大。",
    "innateskill3": "魅惑之眼",
    "innateskill1info3": "血月平原吸血鬼能够通过魅惑之眼使敌人短暂失去行动能力。",
    "healthpoint": 400,
    "maxmagicpoint": 0,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 20,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 20,
    "physicaldefense": 5,
    "magicdefense": 5
  },
  {
    "id": 37,
    "name": "深渊洞穴兽人",
    "innateskill1": "狂暴之力",
    "innateskill1info1": "深渊洞穴兽人能够在战斗中激发狂暴之力，提升攻击力和抗打击能力。",
    "innateskill2": "撕裂猛击",
    "innateskill1info2": "深渊洞穴兽人能够用巨力撕裂敌人的护甲，造成大量物理伤害。",
    "innateskill3": "狂战士之魂",
    "innateskill1info3": "深渊洞穴兽人在生命值低于一定程度时进入狂战士状态，提高攻击速度和致命一击几率。",
    "healthpoint": 200,
    "maxmagicpoint": 0,
    "sturdypoint": 10,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 0,
    "physicaldefense": 5,
    "magicdefense": 5
  },
  {
    "id": 38,
    "name": "幽冥森林妖精",
    "innateskill1": "幻影之舞",
    "innateskill1info1": "幽冥森林妖精能够在战斗中施展幻影之舞，迷惑敌人并闪避攻击。",
    "innateskill2": "毒液之吻",
    "innateskill1info2": "幽冥森林妖精能够对敌人施展毒液之吻，使其中毒并持续受到伤害。",
    "innateskill3": "魅惑之歌",
    "innateskill1info3": "幽冥森林妖精能够通过魅惑之歌使敌人短暂失去抵抗能力。",
    "healthpoint": 0,
    "maxmagicpoint": 200,
    "sturdypoint": 0,
    "stamina": 0,
    "dexterity": 20,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 10,
    "physicaldefense": 5,
    "magicdefense": 5
  },
  {
    "id": 39,
    "name": "黑暗荒原地狱犬",
    "innateskill1": "火焰之牙",
    "innateskill1info1": "黑暗荒原地狱犬能够在攻击时释放火焰之牙，造成额外的火焰伤害。",
    "innateskill2": "地狱火焰",
    "innateskill1info2": "黑暗荒原地狱犬能够召唤地狱火焰，灼烧周围的敌人。",
    "innateskill3": "暗影疾走",
    "innateskill1info3": "黑暗荒原地狱犬能够进入暗影疾走状态，增加移动速度并避开攻击。",
    "healthpoint": 300,
    "maxmagicpoint": 0,
    "sturdypoint": 5,
    "stamina": 5,
    "dexterity": 5,
    "spiritualintuition": 5,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 10,
    "physicaldefense": 0,
    "magicdefense": 0
  },
  {
    "id": 40,
    "name": "炼狱山脉恶魔",
    "innateskill1": "地狱之火",
    "innateskill1info1": "炼狱山脉恶魔能够召唤地狱之火，焚烧敌人并造成持续伤害。",
    "innateskill2": "恶魔之爪",
    "innateskill1info2": "炼狱山脉恶魔拥有强大的恶魔之爪，能够撕裂敌人的护甲并造成严重伤害。",
    "innateskill3": "恐惧之吼",
    "innateskill1info3": "炼狱山脉恶魔能够发出恐惧之吼，使周围的敌人陷入恐慌。",
    "healthpoint": 400,
    "maxmagicpoint": 0,
    "sturdypoint": 5,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 10,
    "luckyvalue": 20,
    "intelligence": 0,
    "faith": 0,
    "attack": 20,
    "armourclass": 5,
    "physicaldefense": 10,
    "magicdefense": 10
  },
  {
    "id": 41,
    "name": "邪影山谷梦魇",
    "innateskill1": "梦魇侵蚀",
    "innateskill1info1": "邪影山谷梦魇能够侵蚀敌人的精神，使其陷入恐惧和幻觉。",
    "innateskill2": "暗影步",
    "innateskill1info2": "邪影山谷梦魇能够在战斗中利用暗影步迅速接近或远离敌人。",
    "innateskill3": "噩梦之触",
    "innateskill1info3": "邪影山谷梦魇能够通过噩梦之触削弱敌人的力量和意志。",
    "healthpoint": 500,
    "maxmagicpoint": 10,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 10,
    "faith": 10,
    "attack": 0,
    "armourclass": 0,
    "physicaldefense": 0,
    "magicdefense": 0
  },
  {
    "id": 42,
    "name": "幽影荒漠亡魂",
    "innateskill1": "幽灵之触",
    "innateskill1info1": "幽影荒漠亡魂能够通过幽灵之触削弱敌人的生命力，并吸取部分生命能量。",
    "innateskill2": "死亡之影",
    "innateskill1info2": "幽影荒漠亡魂能够释放死亡之影，使周围的敌人陷入恐慌并持续受到伤害。",
    "innateskill3": "幽灵漫步",
    "innateskill1info3": "幽影荒漠亡魂能够在战斗中进行幽灵漫步，迅速穿越敌人的防线并造成混乱。",
    "healthpoint": 100,
    "maxmagicpoint": 20,
    "sturdypoint": 10,
    "stamina": 0,
    "dexterity": 10,
    "spiritualintuition": 0,
    "luckyvalue": 0,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 20,
    "physicaldefense": 10,
    "magicdefense": 10
  },
  {
    "id": 43,
    "name": "暗影湮灭者",
    "innateskill1": "暗影之触",
    "innateskill1info1": "暗影湮灭者能够通过暗影之触侵入敌人的精神世界，造成精神损伤和恐惧效果。",
    "innateskill2": "虚空融合",
    "innateskill1info2": "暗影湮灭者能够融合虚空的力量，暂时提升自身的魔法抵抗和幽灵形态。",
    "innateskill3": "黑暗之怒",
    "innateskill1info3": "暗影湮灭者能够释放黑暗之怒，对周围的敌人造成巨大的暗影伤害和恐慌。",
    "healthpoint": 300,
    "maxmagicpoint": 0,
    "sturdypoint": 20,
    "stamina": 0,
    "dexterity": 0,
    "spiritualintuition": 0,
    "luckyvalue": 10,
    "intelligence": 0,
    "faith": 0,
    "attack": 10,
    "armourclass": 10,
    "physicaldefense": 10,
    "magicdefense": 30
  }
]
